// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	chi "github.com/go-chi/chi"

	mock "github.com/stretchr/testify/mock"
)

// Base is an autogenerated mock type for the Base type
type Base struct {
	mock.Mock
}

// SetUpRoutes provides a mock function with given fields: _a0
func (_m *Base) SetUpRoutes(_a0 *chi.Mux) {
	_m.Called(_a0)
}
